# 파일 다루기
- 파일 열기 open(), with로 열기
- csv, xlsx 파일 다루기
- zip 파일 다루기
- 폴더 내 파일 목록 다루기 (glob, listdir)
- 폴더/파일 생성과 삭제

In [1]:
import numpy as np
from numpy.random import rand
import csv

##  숫자 데이터  파일 생성

In [2]:
n=5
lines =10
with open('test_1.csv', 'w', encoding='UTF8') as f:
    writer = csv.writer(f)
    for i in range(lines):
        row = []
        for i in range(n):
            row.append(round(rand(),3)) # 임의의 랜덤 넘버 생성 (소수점 3자리)
        writer.writerow(row)

In [4]:
!cat test_1.csv # 맥에서
# !type test_1.csv # 윈도우에서

## 숫자 데이터 읽기

In [5]:
# 텍스트 형태로 통으로 읽기
with open('test_1.csv', 'r', encoding='UTF8') as f:
    data = f.read()
data

'0.55,0.172,0.292,0.055,0.086\n0.813,0.376,0.271,0.292,0.455\n0.477,0.643,0.857,1.0,0.98\n0.144,0.804,0.181,0.61,0.815\n0.965,0.334,0.194,0.68,0.035\n0.546,0.143,0.627,0.112,0.786\n0.85,0.151,0.404,0.84,0.756\n0.777,0.551,0.409,0.461,0.68\n0.017,0.047,0.762,0.44,0.642\n0.671,0.413,0.868,0.658,0.047\n'

In [6]:
# 리스트 형태로 행단위로 읽기
with open('test_1.csv', 'r', encoding='UTF8') as f:
    data = f.readlines()
    print(data)

['0.55,0.172,0.292,0.055,0.086\n', '0.813,0.376,0.271,0.292,0.455\n', '0.477,0.643,0.857,1.0,0.98\n', '0.144,0.804,0.181,0.61,0.815\n', '0.965,0.334,0.194,0.68,0.035\n', '0.546,0.143,0.627,0.112,0.786\n', '0.85,0.151,0.404,0.84,0.756\n', '0.777,0.551,0.409,0.461,0.68\n', '0.017,0.047,0.762,0.44,0.642\n', '0.671,0.413,0.868,0.658,0.047\n']


In [7]:
type(data[0])

str

In [10]:
data[0]*3

'0.55,0.172,0.292,0.055,0.086\n0.55,0.172,0.292,0.055,0.086\n0.55,0.172,0.292,0.055,0.086\n'

In [11]:
# 한 라인씩 읽어서 처리하기
with open('test_1.csv', 'r', encoding='UTF8') as f:
    while True:
        line = f.readline()
        if not line: 
            break
        print(line)

0.681,0.184,0.58,0.804,0.707

0.938,0.091,0.127,0.611,0.401

0.721,0.638,0.689,0.46,0.332

0.103,0.028,0.74,0.139,0.55

0.245,0.347,0.385,0.07,0.059

0.264,0.686,0.691,0.995,0.78

0.693,0.068,0.672,0.694,0.642

0.165,0.482,0.524,0.213,0.252

0.963,0.45,0.428,0.282,0.268

0.103,0.369,0.921,0.82,0.669



In [12]:
# 일부만 읽어서 처리하기
with open('test_1.csv', 'r', encoding='UTF8') as f:
    for i in range(3):
        line = f.readline()
        print(line)

0.55,0.172,0.292,0.055,0.086

0.813,0.376,0.271,0.292,0.455

0.477,0.643,0.857,1.0,0.98



In [14]:
# 어레이로 읽기 (일부만 읽기)
from numpy import genfromtxt
array_data = genfromtxt('test_1.csv', delimiter=',', max_rows=4)
array_data*1000

array([[ 550.,  172.,  292.,   55.,   86.],
       [ 813.,  376.,  271.,  292.,  455.],
       [ 477.,  643.,  857., 1000.,  980.],
       [ 144.,  804.,  181.,  610.,  815.]])

In [20]:
import pandas as pd
pd.read_csv('test_1.csv', header=0)

0.55  0.172  0.292  0.055  0.086
0  0.813  0.376  0.271  0.292  0.455
1  0.477  0.643  0.857  1.000  0.980
2  0.144  0.804  0.181  0.610  0.815
3  0.965  0.334  0.194  0.680  0.035
4  0.546  0.143  0.627  0.112  0.786
5  0.850  0.151  0.404  0.840  0.756
6  0.777  0.551  0.409  0.461  0.680
7  0.017  0.047  0.762  0.440  0.642
8  0.671  0.413  0.868  0.658  0.047

In [58]:
# 일부 컬럼만 사용하기
array_data[:,[0,2]]

array([[0.006, 0.581],
       [0.314, 0.724],
       [0.471, 0.256],
       [0.702, 0.261]])

## 문자 데이터 쓰기

In [16]:
# 쓰기 전용으로 파일 열기 (write)
# 파일이 없으면 새로 만든다
f = open("test.csv", "w")
f.write("a,b,c,d,e \n")
f.write("1,2,3,4,5 \n")
f.close()

In [17]:
# 파일 내용 보기
with open('test.csv') as f:
    contents = f.read()
    print(contents)

a,b,c,d,e 
1,2,3,4,5 



In [18]:
# 파일 내용 일부 읽기
with open('test.csv') as f:
    contents = f.read(30)
    print(contents)

a,b,c,d,e 
1,2,3,4,5 



### with 사용
- 파일을 열 때 with를 사용하면, 해당 블록을 나갈 때 열린 파일을 닫는다
- 즉, close 호출을 잊어버려도 안전하게 파일을 닫는다

In [19]:
# 운영체제 명령으로 보기
# !cat test.csv  # 리눅스나 맥에서
# !type test.csv # 윈도우에서

### 파일 오픈 옵션
'r'	읽기 (디폴트)  
'w'	쓰기 (파일이 없었으면 새로 생성하며 이미 있었으면 덮어쓴다)  
'a'	맨 뒤에 추가 (appending), 파일이 없었으면 새로 생성  
't'	텍스트 모드로 오픈 (디폴트)  
'b'	바이너리 모드로 오픈  
'+'	읽기 쓰기 모두 가능  

In [20]:
# 기존 파일에 추가하는 옵션으로 파일 열기 (append)
with open("test.csv", "a") as f:
    f.write("6,7,8,9,10 \n")
    f.write("11,12,13,14,15 \n")
    f.write("16,17,18,19,20 \n")

### 한번에 모두 읽기, read()

In [21]:
with open('test.csv') as f: 
    print(f.read())

a,b,c,d,e 
1,2,3,4,5 
6,7,8,9,10 
11,12,13,14,15 
16,17,18,19,20 



### 한줄씩 읽기, readline()

In [22]:
with open("test.csv",'r') as f:
    while True:
        line = f.readline()
        if not line: 
            break
        print(line)

a,b,c,d,e 

1,2,3,4,5 

6,7,8,9,10 

11,12,13,14,15 

16,17,18,19,20 



### 한번에 모두 읽어 라인단위로 리스트 만들기,  readlines()

In [23]:
with open("test.csv",'r') as f:
    lines = f.readlines()
    print(lines)

['a,b,c,d,e \n', '1,2,3,4,5 \n', '6,7,8,9,10 \n', '11,12,13,14,15 \n', '16,17,18,19,20 \n']


## 어레이로 읽기
- 문자열을 숫자로 취급한다

In [28]:
array_data = genfromtxt('test.csv', delimiter=',', max_rows=4)
array_data*100

array([[  nan,   nan,   nan,   nan,   nan],
       [ 100.,  200.,  300.,  400.,  500.],
       [ 600.,  700.,  800.,  900., 1000.],
       [1100., 1200., 1300., 1400., 1500.]])

## csv 파일을 데이터프레임으로 바로 읽기

In [24]:
import pandas as pd 

df = pd.read_csv('test.csv')  
df
# 디폴트로 첫 행을 컬럼명으로 사용한다

a   b   c   d  e 
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20

### 첫 행도 데이터로 취급하기
- 헤더(컬럼명 등)가 없는 경우, 즉 데이터만 들어있는 경우
- header=None 사용
- 여러 행의 헤더가 있는 경우는 header= 2 등으로 행을 제거한다

In [25]:
pd.read_csv('test.csv', header=None) 

0   1   2   3    4
0   a   b   c   d   e 
1   1   2   3   4   5 
2   6   7   8   9  10 
3  11  12  13  14  15 
4  16  17  18  19  20

In [26]:
pd.read_csv('test.csv', header=2) # 상위 세개의 행 제거

6   7   8   9  10 
0  11  12  13  14   15
1  16  17  18  19   20

In [27]:
# 컬럼명 지정하기
pd.read_csv('test.csv', names=['A','B','C','D','E'])

A   B   C   D    E
0   a   b   c   d   e 
1   1   2   3   4   5 
2   6   7   8   9  10 
3  11  12  13  14  15 
4  16  17  18  19  20

In [55]:
# 일부 행만 읽기 nrows 사용
df2 = pd.read_csv('test.csv', nrows=2)
df2

a  b  c  d  e 
0  1  2  3  4   5
1  6  7  8  9  10

In [57]:
# 일부 행만 리스트로 읽기(대용량 데이터의 경우), readline() 사용
number_of_lines = 3

out = []
with open('test.csv') as f: 
    for i in range(number_of_lines):
        line = f.readline()
        out.append(line)
out

['a,b,c,d,e \n', '1,2,3,4,5 \n', '6,7,8,9,10 \n']

## csv 파일로 출력
- 판다스의 to_csv() 사용

In [13]:
df.to_csv('output.csv')

In [14]:
with open('output.csv') as f: print(f.read())

,a,b,c,d,e 
0,1,2,3,4,5
1,6,7,8,9,10
2,11,12,13,14,15
3,16,17,18,19,20



- 데이터 프레임의 인덱스도 포함되어 저장된다
- 인덱스를 제거하려면, index=False 를 지정한다

In [15]:
df.to_csv('output.csv', index=False)
with open('output.csv') as f: print(f.read())

a,b,c,d,e 
1,2,3,4,5
6,7,8,9,10
11,12,13,14,15
16,17,18,19,20



In [16]:
# csv 파일 읽기
# 앞의 pandas 예제에서 cities.csv를 만들어 저장한 경우
# df2 = pd.read_csv('cities.csv')  
df2 = pd.read_csv('output.csv')  
df2

a   b   c   d  e 
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20

### 액셀 파일 읽기

In [17]:
# 앞의 pandas 예제에서 cities.xlsx 를 만들어 저장한 경우
# df2 = pd.read_excel('cities.xlsx')  
# df2

### 액셀 한글 인코딩
- 문자의 인코딩은 기본적으로 utf-8 을 사용한다
- 그러나 한글의 경우 다른 인코딩으로 저장되는 경우가 있다
 - MS 액셀에서 csv로 저장할 때 한글이 cpc949로 인코딩된다. 이때는 아래 옵션이 필요하다
 - encoding = 'cpc949'
 - encoding = 'EUK-KR'을 선택해야 하는 경우도 있다

## zip 파일 만들기

In [18]:
import zipfile
with zipfile.ZipFile('output.zip', 'w') as myzip:
    myzip.write('output.csv')

### zip 파일 풀기

In [19]:
with zipfile.ZipFile("output.zip", 'r') as zf: 
    print(zf.namelist()) # 포한된 파일명 보기
    zf.extractall() # 하위 폴더 지정 가능

['output.csv']


# 폴더 작업

## 현재 폴더 위치 보기

In [21]:
import os
cur_dir = os.getcwd()
cur_dir

'/Users/hwa-kim/Dropbox/lab/book12'

## 폴더의 파일 목록 얻기
- glob() 사용
- listdir() 사용

### glob()를 사용

In [22]:
# 파일 목록 얻기
from glob import glob
sorted(glob('f_*'))

['f_01_Python.ipynb',
 'f_02_Pandas.ipynb',
 'f_03_Numpy.ipynb',
 'f_04_File.ipynb',
 'f_05_Function.ipynb',
 'f_06_Preprocessing.ipynb',
 'f_07_Preprocessing_Example.ipynb',
 'f_08_Table.ipynb',
 'f_09_Groupby.ipynb',
 'f_10_LinearPrediction.ipynb',
 'f_11_MachineLearning.ipynb',
 'f_12_GD.ipynb',
 'f_13_Classification.ipynb',
 'f_14_Ranking_PRCurve.ipynb',
 'f_15_LogisticRegression.ipynb',
 'f_16_Ranking_proba.ipynb',
 'f_17_DecisionTree.ipynb',
 'f_18_SVM.ipynb',
 'f_19_ModelComparison.ipynb',
 'f_20_Ensemble.ipynb',
 'f_21_StatisticsBasic.ipynb',
 'f_22_FeatureEngineering.ipynb',
 'f_23_Clustering.ipynb',
 'f_24_ClusteringExample.ipynb',
 'f_25_MultiOutput.ipynb',
 'f_26_TimeseriesOutput.ipynb',
 'f_27_TimeseriesForecasting.ipynb',
 'f_28_Prophet.ipynb',
 'f_29_ProphetAdvanced.ipynb',
 'f_30_AddFeatures.ipynb',
 'f_31_XY_Model.ipynb',
 'f_32_PM.ipynb',
 'f_33_MLP_CNN.ipynb',
 'f_34_PatternRecognition.ipynb',
 'f_35_Image_Recognition.ipynb',
 'f_36_TransferLearning.ipynb',
 'f_37_LS

### listdir()를 사용

In [23]:
# 파일과 폴더 목록 얻기
file_list = os.listdir()
sorted(file_list)

['.DS_Store',
 '.ipynb_checkpoints',
 '.tmp.drivedownload',
 'DX_Motor.ipynb',
 'LGadd2',
 'LGadd2.zip',
 'Merged_excel.xlsx',
 'NGdata1.zip',
 'PM_train_pre.csv',
 'SET_angle_V2.ipynb',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 '__MACOSX',
 'a_01_Python_Intro.ipynb',
 'a_02_pandas.ipynb',
 'a_03_numpy.ipynb',
 'chromedriver',
 'competitive-data-science-predict-future-sales',
 'customer.csv',
 'datasalon-master',
 'digit2.png',
 'digit9-2.png',
 'digit9.png',
 'digits-lin.pkl',
 'digits.pkl',
 'down.zip',
 'down2.zip',
 'energy.csv',
 'face-detect.png',
 'face-pickup.png',
 'families.jpg',
 'g_45_yolo.ipynb',
 'g_46_Yolo5_ing.ipynb',
 'g_54_토픽모델링.ipynb',
 'g_60_0_선형프로그래밍.ipynb',
 'g_60_1_정수형선형프로그래밍.ipynb',
 'g_60_2_매트릭스형선형최적화.ipynb',
 'g_60_3_제약프로그래밍.ipynb',
 'g_60_4_배정.ipynb',
 'g_60_5_라우팅기초.ipynb',
 'g_60_6_비클라우팅.ipynb',
 'g_60_7_라우팅고급.ipynb',
 'g_60_8_OR_응용.ipynb',
 'g_61_1_물류최적화개념.ipynb',
 '

In [24]:
# 파일의 전체 경로, full path 만들기
cur_dir = os.getcwd()
for file_name in file_list:
    full_path = os.path.join(cur_dir, file_name)
    print(full_path)

/Users/hwa-kim/Dropbox/lab/book12/h_02_pandas.ipynb
/Users/hwa-kim/Dropbox/lab/book12/h_48_언어모델링.ipynb
/Users/hwa-kim/Dropbox/lab/book12/test_1.csv
/Users/hwa-kim/Dropbox/lab/book12/LGadd2
/Users/hwa-kim/Dropbox/lab/book12/hh_20_앙상블알고리즘.ipynb
/Users/hwa-kim/Dropbox/lab/book12/hh_34_오염예측_LSTM.ipynb
/Users/hwa-kim/Dropbox/lab/book12/g_45_yolo.ipynb
/Users/hwa-kim/Dropbox/lab/book12/g_71_1_Molecular_Visualization_using_RDkit.ipynb
/Users/hwa-kim/Dropbox/lab/book12/h_90_series_clustering.ipynb
/Users/hwa-kim/Dropbox/lab/book12/h_36_1_디지털필터출력.ipynb
/Users/hwa-kim/Dropbox/lab/book12/hh_34_시계열_rnn_사인파.ipynb
/Users/hwa-kim/Dropbox/lab/book12/DX_Motor.ipynb
/Users/hwa-kim/Dropbox/lab/book12/hh_29_시계열예측_자전거대여.ipynb
/Users/hwa-kim/Dropbox/lab/book12/plot_Filtering.ipynb
/Users/hwa-kim/Dropbox/lab/book12/make_blur_noise (1).ipynb
/Users/hwa-kim/Dropbox/lab/book12/g_60_2_매트릭스형선형최적화.ipynb
/Users/hwa-kim/Dropbox/lab/book12/g_60_

### 폴더 찾기

In [25]:
for file_name in file_list:
    if os.path.isdir(file_name):
        print("폴더:", file_name)

폴더: LGadd2
폴더: competitive-data-science-predict-future-sales
폴더: .tmp.drivedownload
폴더: __MACOSX
폴더: yolov5
폴더: datasalon-master
폴더: personal_info
폴더: .ipynb_checkpoints


## 기타 폴더 및 파일 관리
### os 패키지에서
- 폴더 생성 mkdir()
- 폴더 위치 이동 chdir()
- 파일 이름 변경 rename()
- 파일 삭제 remove()
- 폴더 삭제 rmdir()

In [39]:
!ls d*

digit2.png     digit9.png     digits.pkl     down2.zip
digit9-2.png   digits-lin.pkl down.zip

data:

datasalon-master:
01_초판                  README.md
02_개정판


In [37]:
# 폴더가 없으면 새로 만들기
if not os.path.exists("./data"):
    os.mkdir("./data")

In [38]:
# (참고) 폴더가 있으면 "지우고" 새로 만들기
if os.path.exists("./data"):
    os.rmdir("./data")
    os.mkdir("./data")

In [40]:
# 폴더 이동
os.chdir('./data')

In [41]:
os.getcwd()

'/Users/hwa-kim/Dropbox/lab/book12/data'

In [29]:
# 폴더 이동
os.chdir('../')

In [30]:
os.getcwd()

'/Users/hwa-kim/Dropbox/lab/book12'

In [31]:
# 파일 이름 변경
os.rename('output.csv','new_output.csv')
with open('new_output.csv') as f: print(f.read())

a,b,c,d,e 
1,2,3,4,5
6,7,8,9,10
11,12,13,14,15
16,17,18,19,20



In [32]:
# 파일 삭제
os.remove('new_output.csv')

In [33]:
# 폴더 삭제
os.rmdir('./data')